### ISSUE TITLE
Official community crate

### ISSUE THREAD

**Issue by hecrj** [iced-rs/iced_audio#11]
Hey @BillyDM!

I've been thinking about ways to start gathering a community around `iced` together and I was wondering if you would like to join [the `iced-rs` organization](https://github.com/iced-rs), transfer this repository there, and kind of make it the "official, community-driven widget crate for audio". I willl move the main repository there too eventually, so I believe it could help with visibility and bring new contributors.

See [this Zulip thread](https://iced.zulipchat.com/#narrow/stream/213316-general/topic/Community.20involvement.20ideas) for a bit of additional context.

**Comment by BillyDM** [comment]
Sure! That sounds like a good idea.

**Comment by hecrj** [comment]
Cool! I have invited you to join the `iced-rs` organization. You should be able to transfer the repository there once you accept the invitation.

**Comment by BillyDM** [comment]
Done!
